version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        environment:
            - DEBUG=1
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - DEBUG=1
    database:
        build:
            context: ./
            dockerfile: deploy/db.docker
        environment:
            - "MYSQL_ROOT_PASSWORD=pass"
            - "MYSQL_DATABASE=adoptimizer"
            - "MYSQL_USER=hoge"
            - "MYSQL_PASSWORD=fuga"
        ports:
            - "33061:3306"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
    cache:
        image: memcached:1.4.31
        ports:
            - "11311:11211"
